from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import relationship
from app.core.database import Base


class ScanRecord(Base):
    __tablename__ = "scan_records"

    id = Column(Integer, primary_key=True, index=True)
    client_uuid = Column(String(64), unique=True, index=True, nullable=False)   # UUID generated by mobile SQLite
    worker_id = Column(Integer, ForeignKey("workers.id"), nullable=False)
    badge_id = Column(Integer, ForeignKey("badges.id"), nullable=True)

    # Shift & Location Information
    shift_type = Column(String(20), default="SHIFT_A")                         # SHIFT_A (06:00-14:00), SHIFT_B, SHIFT_C
    scan_event = Column(String(20), default="EXIT")                            # ENTRY / EXIT / ROUTINE
    location_name = Column(String(200), default="Refinery Area 4 - Crude Distillation Unit")
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)

    # Environmental Data Fusion
    ambient_temp_c = Column(Float, default=28.5)
    relative_humidity = Column(Float, default=62.0)
    weather_source = Column(String(50), default="Local SCADA Telemetry")       # SCADA / Weather API

    # Computer Vision Colorimetric Extraction (CIE LAB)
    extracted_L = Column(Float, nullable=False)
    extracted_a = Column(Float, nullable=False)
    extracted_b = Column(Float, nullable=False)
    delta_E = Column(Float, nullable=False)                                     # Color distance from baseline

    # AI Dosimeter Calculated Metrics
    exposure_hours = Column(Float, default=8.0)
    cumulative_dosage_ppm_hr = Column(Float, nullable=False)                   # Cumulative dosage
    avg_concentration_ppm = Column(Float, nullable=False)                      # Shift TWA
    
    # Compliance & Safety Status
    compliance_status = Column(String(30), default="NORMAL")                   # NORMAL, ACTION_REQUIRED, DANGER_EXCEEDED
    dgms_compliant = Column(Boolean, default=True)
    oisd_compliant = Column(Boolean, default=True)
    
    scanned_at = Column(DateTime, default=datetime.utcnow)
    synced_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    worker = relationship("Worker", back_populates="scans")
    badge = relationship("Badge", back_populates="scans")
